# Pre-commit configuration for markdown-flow-agent-py
# Automatically formats, lints, and validates Python code before commits
#
# To install: pre-commit install
# To run manually: pre-commit run --all-files

repos:
  # =============================================================================
  # Basic file checks and fixes
  # =============================================================================
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      # File content fixes
      - id: end-of-file-fixer
        description: Ensures files end with a newline
      - id: trailing-whitespace
        description: Removes trailing whitespace
        args: [--markdown-linebreak-ext=md]

      # File format validation
      - id: check-yaml
        description: Validates YAML file syntax
      - id: check-json
        description: Validates JSON file syntax
      - id: check-toml
        description: Validates TOML file syntax

      # Git-related checks
      - id: check-merge-conflict
        description: Checks for merge conflict markers
      - id: check-case-conflict
        description: Checks for case conflicts in filenames
      - id: check-symlinks
        description: Checks for broken symlinks

      # Python-specific checks
      - id: check-ast
        description: Validates Python AST
      - id: check-builtin-literals
        description: Checks for builtin type constructor use
      - id: check-docstring-first
        description: Checks that docstrings come first
      - id: debug-statements
        description: Checks for debugger imports and statements
      - id: name-tests-test
        description: Ensures test files are named correctly
        args: [--pytest-test-first]

  # =============================================================================
  # Python code formatting and linting (Ruff - modern replacement for Black/Flake8/isort)
  # =============================================================================
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.11
    hooks:
      # Linting (replaces Flake8 + many other tools)
      - id: ruff-check
        description: Run Ruff linter with auto-fixes
        args: [--fix, --exit-non-zero-on-fix]

      # Code formatting (replaces Black)
      - id: ruff-format
        description: Run Ruff formatter

  # =============================================================================
  # Type checking
  # =============================================================================
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.1
    hooks:
      - id: mypy
        description: Static type checking with mypy (basic checks only)
        additional_dependencies: [typing_extensions]
        args: [
          --ignore-missing-imports,
          --follow-imports=silent,
          --no-strict-optional,
          --allow-untyped-defs,
          --allow-incomplete-defs,
          --no-warn-no-return,
          --show-error-codes
        ]

  # =============================================================================
  # Commit message validation
  # =============================================================================
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.8.3
    hooks:
      - id: commitizen
        description: Validates commit messages follow Conventional Commits
        stages: [commit-msg]
